filebeat.inputs:
  - type: filestream
    id: selenium-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "selenium-automation-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "selenium-automation-logs"
setup.template.pattern: "selenium-automation-logs-*"

logging.level: info
