baseUrl=https://expense-tracker-psi-beryl.vercel.app/sign-in
apiURL=https://fakestoreapi.com
headless=false
implicitWait=5
explicitWait=20
pageLoadTimeout=30
api.timeout=30
jsonFilePath=./src/main/resources/testdata/users.json
retryCount=1
runMode=local
remoteUrl=http://localhost:4444/wd/hub